title: Xoptfoil2
description: Documentation
theme: just-the-docs
url: https://jxjo.github.io/Xoptfoil2
baseurl: /docs # the subpath of your site, e.g. /blog

aux_links:
  Xoptfoil2 on Github: https://github.com/jxjo/Xoptfoil2

# Set a path/url to a logo that will be displayed instead of the title
logo: "/images/Xoptfoil2_logo.png"

# favicon - made with https://redketchup.io/favicon-generator  - Roboto condensed
favicon_ico: "/images/XO2.ico"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jxjo/Xoptfoil2" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately


# table of content TOC
kramdown: 
  toc_levels: "1,2,3" 

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
    opacity: 0.1
  warning:
    title: Warning
    color: red  
  tip:
    title: Tip
    color: blue
    opacity: 0.1